{{- if .Values.combinedIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress-controller.fullname" . }}-combined
  labels:
    {{- include "ingress-controller.labels" . | nindent 4 }}
  {{- with .Values.combinedIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.combinedIngress.className }}
  {{- if .Values.combinedIngress.tls }}
  tls:
    {{- range .Values.combinedIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.combinedIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .service }}-service
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
{{- end }}
