{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-agent.fullname" . }}-secret
  labels:
    {{- include "ai-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}