#!/bin/bash
# Interactive PV/PVC Demonstration Script
# This shows you exactly how PV and PVC work in your cluster

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🎓 PV and PVC Interactive Demo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

NAMESPACE="production"

echo "📝 CONCEPT: Think of it like renting storage"
echo "   PV  = The physical storage locker (building)"
echo "   PVC = Your rental contract (key to locker)"
echo "   Pod = You (using the locker)"
echo ""
read -p "Press Enter to see your actual PV and PVC..."
echo ""

# Step 1: Show PV
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  PersistentVolume (PV) - The Actual Storage"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
kubectl get pv | grep -E "NAME|mongodb" || echo "No PV found yet. Deploy MongoDB first!"
echo ""
echo "💡 This is the 'apartment building' - it exists and is ready"
echo ""
read -p "Press Enter to see PVC..."
echo ""

# Step 2: Show PVC
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  PersistentVolumeClaim (PVC) - The Rental Request"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
kubectl get pvc -n $NAMESPACE | grep -E "NAME|mongodb" || echo "No PVC found yet"
echo ""
echo "💡 This is your 'rental application' - requesting storage"
echo ""
read -p "Press Enter to see the binding..."
echo ""

# Step 3: Show the binding
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  The Binding - PVC ←→ PV"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
kubectl describe pvc -n $NAMESPACE 2>/dev/null | grep -E "Name:|Status:|Volume:|Capacity:|Used By:" | head -10 || echo "No PVC to describe"
echo ""
echo "💡 When STATUS is 'Bound', PVC is connected to PV"
echo ""
read -p "Press Enter to see what the Pod uses..."
echo ""

# Step 4: Show pod using PVC
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4️⃣  Pod Using the Storage"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
kubectl get pods -n $NAMESPACE | grep -E "NAME|mongodb" || echo "No pods found"
echo ""
echo "💡 The pod 'mongodb-0' is the tenant using the storage"
echo ""
read -p "Press Enter to see inside the pod..."
echo ""

# Step 5: Show mount inside pod
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "5️⃣  Inside the Pod - Where MongoDB Writes"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
kubectl exec mongodb-0 -n $NAMESPACE -- df -h /data/db 2>/dev/null || echo "Pod not running"
echo ""
kubectl exec mongodb-0 -n $NAMESPACE -- ls -lh /data/db 2>/dev/null | head -5 || echo "Cannot access pod"
echo ""
echo "💡 MongoDB thinks it's writing to /data/db in the container"
echo ""
read -p "Press Enter to see the host filesystem..."
echo ""

# Step 6: Show host directory
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "6️⃣  On the Host - The Real Storage Location"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Host path: /home/sai/mongo_data"
ls -lh /home/sai/mongo_data 2>/dev/null | head -5 || echo "Cannot access (may need sudo or doesn't exist)"
echo ""
echo "💡 This is where the data ACTUALLY lives on your VPS"
echo ""
read -p "Press Enter to see the complete chain..."
echo ""

# Step 7: Show the complete chain
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "7️⃣  The Complete Storage Chain"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "┌─────────────────────────────────────────────────┐"
echo "│  Pod: mongodb-0                                 │"
echo "│  Container path: /data/db                       │"
echo "│  (MongoDB writes here)                          │"
echo "└─────────────┬───────────────────────────────────┘"
echo "              │"
echo "              │ mounted from"
echo "              ↓"
echo "┌─────────────────────────────────────────────────┐"
echo "│  PVC: data-mongodb-0                            │"
echo "│  Requests: 20Gi                                 │"
echo "│  Status: Bound                                  │"
echo "└─────────────┬───────────────────────────────────┘"
echo "              │"
echo "              │ bound to"
echo "              ↓"
echo "┌─────────────────────────────────────────────────┐"
echo "│  PV: mongodb-pv                                 │"
echo "│  Capacity: 20Gi                                 │"
echo "│  Type: hostPath                                 │"
echo "└─────────────┬───────────────────────────────────┘"
echo "              │"
echo "              │ maps to"
echo "              ↓"
echo "┌─────────────────────────────────────────────────┐"
echo "│  Host Filesystem                                │"
echo "│  Path: /home/sai/mongo_data/                    │"
echo "│  (Physical disk on your VPS)                    │"
echo "└─────────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 KEY INSIGHT:"
echo "   When MongoDB writes to /data/db in the container,"
echo "   it's actually writing to /home/sai/mongo_data on the host!"
echo ""
echo "   They're the SAME files, just different paths."
echo "   Like calling your house 'home' vs '123 Main Street'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press Enter to test data persistence..."
echo ""

# Step 8: Demonstrate persistence
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "8️⃣  Testing Data Persistence"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Let's prove data persists through pod restart:"
echo ""
echo "1. Current pod:"
kubectl get pod -l app.kubernetes.io/name=mongodb -n $NAMESPACE -o wide 2>/dev/null || echo "No pod"
echo ""

read -p "Want to delete the pod and see data persist? (y/N) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Deleting pod..."
    kubectl delete pod mongodb-0 -n $NAMESPACE 2>/dev/null || echo "Pod not found"
    echo ""
    echo "Waiting for new pod to be created..."
    sleep 3
    kubectl get pod -l app.kubernetes.io/name=mongodb -n $NAMESPACE -o wide 2>/dev/null || echo "Still creating..."
    echo ""
    echo "✅ Notice:"
    echo "   - Pod has new name (mongodb-0)"
    echo "   - Same PVC is mounted: data-mongodb-0"
    echo "   - Same PV is used: mongodb-pv"
    echo "   - Same host directory: /home/sai/mongo_data"
    echo "   - All data intact!"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Demo Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Remember:"
echo "   PV  = The physical storage (apartment building)"
echo "   PVC = Request for storage (rental contract)"
echo "   Pod = Uses the storage (tenant)"
echo ""
echo "   They work together to give your app persistent storage!"
echo ""
