apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
