export const INDIAN_BANK_OPTIONS = [
  { value: "State Bank of India", label: "State Bank of India", shortLabel: "SBI", color: "bg-blue-700", domain: "sbi.co.in" },
  { value: "HDFC Bank", label: "HDFC Bank", shortLabel: "HDFC", color: "bg-rose-700", domain: "hdfcbank.com" },
  { value: "ICICI Bank", label: "ICICI Bank", shortLabel: "ICICI", color: "bg-orange-600", domain: "icicibank.com" },
  { value: "Axis Bank", label: "Axis Bank", shortLabel: "AXIS", color: "bg-purple-700", domain: "axisbank.com" },
  { value: "Kotak Mahindra Bank", label: "Kotak Mahindra Bank", shortLabel: "KOTAK", color: "bg-red-600", domain: "kotak.com" },
  { value: "Punjab National Bank", label: "Punjab National Bank", shortLabel: "PNB", color: "bg-amber-600", domain: "pnbindia.in" },
  { value: "Bank of Baroda", label: "Bank of Baroda", shortLabel: "BOB", color: "bg-orange-700", domain: "bankofbaroda.in" },
  { value: "Canara Bank", label: "Canara Bank", shortLabel: "CAN", color: "bg-blue-600", domain: "canarabank.com" },
  { value: "Union Bank of India", label: "Union Bank of India", shortLabel: "UBI", color: "bg-indigo-700", domain: "unionbankofindia.co.in" },
  { value: "Indian Bank", label: "Indian Bank", shortLabel: "IND", color: "bg-cyan-700", domain: "indianbank.in" },
  { value: "Bank of India", label: "Bank of India", shortLabel: "BOI", color: "bg-red-700", domain: "bankofindia.co.in" },
  { value: "Central Bank of India", label: "Central Bank of India", shortLabel: "CBI", color: "bg-sky-700", domain: "centralbankofindia.co.in" },
  { value: "Indian Overseas Bank", label: "Indian Overseas Bank", shortLabel: "IOB", color: "bg-blue-800", domain: "iob.in" },
  { value: "UCO Bank", label: "UCO Bank", shortLabel: "UCO", color: "bg-yellow-600", domain: "ucobank.com" },
  { value: "Punjab and Sind Bank", label: "Punjab and Sind Bank", shortLabel: "PSB", color: "bg-emerald-700", domain: "punjabandsindbank.co.in" },
  { value: "IDFC FIRST Bank", label: "IDFC FIRST Bank", shortLabel: "IDFC", color: "bg-red-700", domain: "idfcfirstbank.com" },
  { value: "IndusInd Bank", label: "IndusInd Bank", shortLabel: "INDUS", color: "bg-emerald-700", domain: "indusind.com" },
  { value: "Yes Bank", label: "Yes Bank", shortLabel: "YES", color: "bg-sky-700", domain: "yesbank.in" },
  { value: "Federal Bank", label: "Federal Bank", shortLabel: "FED", color: "bg-teal-700", domain: "federalbank.co.in" },
  { value: "AU Small Finance Bank", label: "AU Small Finance Bank", shortLabel: "AU", color: "bg-fuchsia-700", domain: "aubank.in" },
  { value: "Bandhan Bank", label: "Bandhan Bank", shortLabel: "BAND", color: "bg-indigo-600", domain: "bandhanbank.com" },
  { value: "RBL Bank", label: "RBL Bank", shortLabel: "RBL", color: "bg-pink-700", domain: "rblbank.com" },
  { value: "South Indian Bank", label: "South Indian Bank", shortLabel: "SIB", color: "bg-indigo-800", domain: "southindianbank.com" },
  { value: "Karnataka Bank", label: "Karnataka Bank", shortLabel: "KBL", color: "bg-red-800", domain: "karnatakabank.com" },
  { value: "Karur Vysya Bank", label: "Karur Vysya Bank", shortLabel: "KVB", color: "bg-green-700", domain: "kvb.co.in" },
  { value: "City Union Bank", label: "City Union Bank", shortLabel: "CUB", color: "bg-violet-700", domain: "cityunionbank.com" },
  { value: "Tamilnad Mercantile Bank", label: "Tamilnad Mercantile Bank", shortLabel: "TMB", color: "bg-blue-700", domain: "tmb.in" },
  { value: "DCB Bank", label: "DCB Bank", shortLabel: "DCB", color: "bg-slate-700", domain: "dcbbank.com" },
  { value: "CSB Bank", label: "CSB Bank", shortLabel: "CSB", color: "bg-green-800", domain: "csb.co.in" },
  { value: "Jammu and Kashmir Bank", label: "Jammu and Kashmir Bank", shortLabel: "JKB", color: "bg-emerald-800", domain: "jkbank.com" },
  { value: "DBS Bank India", label: "DBS Bank India", shortLabel: "DBS", color: "bg-red-700", domain: "dbs.com" },
  { value: "HSBC India", label: "HSBC India", shortLabel: "HSBC", color: "bg-rose-800", domain: "hsbc.co.in" },
  { value: "Standard Chartered Bank", label: "Standard Chartered Bank", shortLabel: "SCB", color: "bg-blue-700", domain: "sc.com" },
  { value: "Deutsche Bank India", label: "Deutsche Bank India", shortLabel: "DB", color: "bg-blue-800", domain: "db.com" },
  { value: "Citibank", label: "Citibank", shortLabel: "CITI", color: "bg-sky-800", domain: "citibank.co.in" },
  { value: "Bank of Maharashtra", label: "Bank of Maharashtra", shortLabel: "BOM", color: "bg-blue-600", domain: "bankofmaharashtra.in" },
  { value: "The Nainital Bank", label: "The Nainital Bank", shortLabel: "NBL", color: "bg-lime-700", domain: "nainitalbank.co.in" },
  { value: "Ujjivan Small Finance Bank", label: "Ujjivan Small Finance Bank", shortLabel: "USFB", color: "bg-orange-600", domain: "ujjivansfb.in" },
  { value: "Equitas Small Finance Bank", label: "Equitas Small Finance Bank", shortLabel: "ESFB", color: "bg-red-600", domain: "equitasbank.com" },
  { value: "Suryoday Small Finance Bank", label: "Suryoday Small Finance Bank", shortLabel: "SSFB", color: "bg-orange-700", domain: "suryodaybank.com" },
  { value: "ESAF Small Finance Bank", label: "ESAF Small Finance Bank", shortLabel: "ESAF", color: "bg-green-700", domain: "esafbank.com" },
  { value: "Fincare Small Finance Bank", label: "Fincare Small Finance Bank", shortLabel: "FIN", color: "bg-purple-600", domain: "fincarebank.com" },
  { value: "Jana Small Finance Bank", label: "Jana Small Finance Bank", shortLabel: "JANA", color: "bg-red-700", domain: "janabank.com" },
  { value: "Utkarsh Small Finance Bank", label: "Utkarsh Small Finance Bank", shortLabel: "UTK", color: "bg-indigo-700", domain: "utkarsh.bank" },
  { value: "North East Small Finance Bank", label: "North East Small Finance Bank", shortLabel: "NESF", color: "bg-cyan-700", domain: "nesfb.com" },
  { value: "India Post Payments Bank", label: "India Post Payments Bank", shortLabel: "IPPB", color: "bg-red-600", domain: "ippbonline.com" },
  { value: "Airtel Payments Bank", label: "Airtel Payments Bank", shortLabel: "APB", color: "bg-rose-600", domain: "airtel.in" },
  { value: "Paytm Payments Bank", label: "Paytm Payments Bank", shortLabel: "PAYTM", color: "bg-sky-600", domain: "paytmbank.com" },
  { value: "Jio Payments Bank", label: "Jio Payments Bank", shortLabel: "JIO", color: "bg-blue-700", domain: "jiopaymentsbank.com" },
];
